/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kostas' at '11/8/16 8:07 PM' with Gradle 2.10
 *
 * @author kostas, @date 11/8/16 8:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
